version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:3000"  
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/crypto_db
      - PORT=3000  
    networks:
      - backend-network

volumes:
  mongo-data:

networks:
  backend-network: